# permissions for end users to view appdbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appdb-viewer-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - appdbs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - appdbs/status
  verbs:
  - get
