# permissions for end users to edit appdbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appdb-editor-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - appdbs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - appdbs/status
  verbs:
  - get
